#!/bin/bash -e

zm_path=$(readlink -f $0)
zm_dir=${zm_path%/*}
SUDO=$(which sudo || true)

set -e 
set -E 

cd $zm_dir

sfs_mpath=/media/sfs
aufs_mpath=/media/aufs
sfs_part_mpath=/media/sfsroot
sfs_root_mpath=$sfs_mpath/root
sfs_home_mpath=$sfs_mpath/home
aufs_root_mpath=$aufs_mpath/aufs_root
aufs_home_mpath=$aufs_mpath/aufs_home
aufs_clean_file_name=.aufs.clean

err()
{   
    echo "Error: $@"
    exit 1
}

version ()
{   
    echo "1.00"
    exit 0
}

backup_file()
{
    bak_file=$1
    if [ -e "$bak_file" ];then
        bak_file_dir=$(dirname $bak_file)/old
        mkdir -p $bak_file_dir
        mv ${bak_file} ${bak_file_dir}
    fi
}

download_file()
{
    src=$1
    dst=$2
    md5=$3
    DL="wget -c"

    if which axel;then
        if [ ! -e "$2" ];then
            axel $1 -o $2
        fi
    else
        wget -c $1 -O $2
    fi

    if [ -n "$md5" ];then
        echo "$md5 $dst" | md5sum -c 
    fi
}

select_continue_debconf ()
{
    echo "#!/bin/bash
    source $zm_dir/common/init_debconf.sh
    db_reset zm_debconf/select_continue
    db_input high zm_debconf/select_continue
    db_go
    db_get zm_debconf/select_continue
    echo \$RET > $build_dir/dbconf_ret
    db_stop
    " > $build_dir/zm_debconf
    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf 2> /dev/null || true

    read ret_select < $build_dir/dbconf_ret
    if [ "$ret_select" = "false" ];then
        exit 1
    fi
}

select_continue()
{
    echo "Continue? y/n"
    read c 
    if [ $c !=  "y" ];then
        err "select no."
    fi
}

get_free_mem_size_m()
{
    free -m | grep Mem | awk '{print $4}'
}

need_root()
{
    if [ "$(id -u)" != "0" ]; then
        err "This function must be run as root" 1>&2
    fi
}

_add_samba_user()
{
    user=$1
    passwd=$2
    echo -e "$passwd\n$passwd" | smbpasswd -a $user -s
}


usage ()
{
    echo "
    Usage:  <options>

    --root-device         [$root_device]
    --home-device         [$home_device]
    --swap-device         [$swap_device]

    --format-disk         format in disk

    --install-grub       

    --arch     [ARCH]     generate system arch, param is [i386 amd64]
    --deb-ver  
    --gen-basesystem      generate base system by debootstrap
    --install-basesystem  install base system 
    --install-system [ device ] install sfssystem 
    --base-system

    --gen-initrd          generate initrd.img
    --gen-sfssystem       generate root.sfs and home.sfs
    --gen-iso-system   generate root.sfs and home.sfs to iso file
    --gen-usb-sfssystem   generate root.sfs and home.sfs to usb disk

    --tar-aufssystem      

    --download-softs      download softs
    --install-softs       install softs

    --setup

    -i, --install             install zm

    --tar-win-files

    --version             Print version.
    --help                Print this help message.
    "
    exit 0
}

print_env()
{
    echo "deb_ver = $deb_ver"
    echo "zm_arch = $zm_arch"
    echo "src_url = $src_url"
    echo "sfs_dir = $sfs_dir"
    echo "zm_user = $zm_user"
    echo "zm_user_dir = $zm_user_dir"
    echo "install_dir = $install_dir"
}

get_dir_res_space()
{
    /bin/df -B1 $1 | awk '{print $4}' | /bin/grep '[[:digit:]]'
}

get_files_size()
{
    files=$1
    filesize=0

    IFS=', '
    for file in $files
    do
        filesize=$(expr $filesize + $(stat -c '%s' $file))
    done
    IFS=' '
    echo $filesize
}

check_file_exist()
{
    test -z $1 && err "Please input check_file_exist() param"

    file=$1
    test -e $file || err "Cann't find file $file."
}

check_removeable_device()
{
    device=$1
    check_file_exist $device

    USBKEYS=($(
    grep -Hv ^0$ /sys/block/*/removable |
    sed s/removable:.*$/device\\/uevent/ |
    xargs grep -H ^DRIVER=sd |
    sed s/device.uevent.*$/size/ |
    xargs grep -Hv ^0$ |
    cut -d / -f 4
    ))
    echo $USBKEYS | grep -w $(basename $device) || err "$device is not remove disk"
}

print_disk_sizeinfo()
{
    if [ $# -gt 0 ];then
        fdisk -l $1 2>&1 | grep '^Disk /dev/.*:' | awk '{print $3$4}'
    fi
}

check_mount()
{
    cat /proc/mounts | grep "$1" > /dev/null
}

mount_device()
{
    $SUDO mount $@
    last_param=${!#}

    if [ ! -e $build_dir/.mount_devs ];then
        touch $build_dir/.mount_devs
    fi

    if grep "$last_param" $build_dir/.mount_devs > /dev/null;then
        echo "$last_param have mounted."
        return
    fi

    tmpfile=$build_dir/.mount_devs.temp
    (echo "$last_param" | cat - $build_dir/.mount_devs > $tmpfile) && mv $tmpfile $build_dir/.mount_devs
}

umount_device()
{
    if [ -e $build_dir/.mount_devs ];then
        $SUDO sh -c "cat /proc/mounts | grep $1 > /dev/null && umount $1 && sed -i \":^$1$:d\" $build_dir/.mount_devs || true"
    fi
}

sfs2dev()
{
    filename=$1
    device=$2
    restore_dir=$3

    echo -n "[ $FUNCNAME ] $filename -> $device "
    check_file_exist $filename
    check_file_exist $device

    mount_device $device $mnt_dir

    if [ ! -d $mnt_dir/$restore_dir ]; then 
        mkdir -p $mnt_dir/$restore_dir -m 0755
    fi
    sfs2dir $filename $mnt_dir/$restore_dir

    umount_device $mnt_dir
}

update_label()
{
    device=$1
    label=$2
    real_label=`e2label $device`
    if [ '$real_label' != '$label' ];then
        e2label $device $label
    fi
}

update_grub_config()
{
    gen_default_grub_config /dev/disk/by-label/sfsroot
}

defalut_install_dir()
{
    install_dir=$1
    if [ -z "$install_dir" -a $# = 2 ];then
        install_dir="$2"
    fi
    if [ -z "$install_dir" ];then
        install_dir=$sfs_dir
        if [ ! -d $sfs_dir ];then
            mkdir -p ${sfs_part_mpath}
            mount_device LABEL=sfsroot ${sfs_part_mpath}
        fi
    fi
    check_file_exist $install_dir
}

install_grub()
{
    grub_device=$1
    echo "[ $FUNCNAME ] grub -> $grub_device  "

    grub_device=`readlink -f $grub_device`
    check_file_exist $grub_device

    select_continue now

    #恢复主扇区
    #  /sbin/install-mbr $(echo ${grub_device} | tr -d [0-9])
    #激活扇区
    # sfdisk -A11 ${grub_device}

    mount_device $grub_device $mnt_dir
    install_grub_on_dir $mnt_dir
    if [ -e $mnt_dir/boot/grub/config/default.cfg ];then
        echo "Overwrite $mnt_dir/boot/grub/config/default.cfg ?"
        select_continue now
    fi
    grub-mkdevicemap -m $mnt_dir/boot/grub/device.map
    # mount_device --bind /dev $mnt_dir/dev
    # chroot $mnt_dir grub-mkconfig -o /boot/grub/grub.cfg
    # umount_device $mnt_dir/dev
    disk_device=${grub_device/p[0-9]*}
    if [ "$disk_device" == "$grub_device" ];then
        disk_device=${grub_device/[0-9]*}
    fi
    grub-install $disk_device --no-floppy --root-directory=$mnt_dir --modules="biosdisk part_msdos"
    umount_device $mnt_dir
}

install_grub_on_dir()
{
    install_dir=$1
    check_file_exist $install_dir
    if [ ! -d $install_dir/boot ];then
        $CP $sfs_part_mpath/boot $install_dir
    fi
    # mkdir -p $install_dir/boot/grub
    # $CP /usr/lib/grub/i386-pc $install_dir/boot/grub/
}

format_usb_device()
{
    usb_device=$1
    check_removeable_device $usb_device

    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    if check_mount $usb_device;then 
        err "$usb_device is mounted!"
    fi

    total_size=` fdisk -l $usb_device | grep Disk | awk '{print $5}'`
    total_cyln=`echo $total_size/255/63/512 | bc`

    diskinfo=` sfdisk -H 255 -S 63 -C $total_cyln -l $usb_device | grep Disk`
    cylns=`echo $diskinfo | awk '{print $3}'`
    heads=`echo $diskinfo | awk '{print $5}'`
    sectors=`echo $diskinfo | awk '{print $7}'`
    disksize=`echo "$cylns*$heads*$sectors*512" | bc`
    echo disksize = $disksize
    ext2_size_bytes=2500000000
    fat_cyln=`echo "($disksize-$ext2_size_bytes)/$heads/$sectors/512" | bc`
    fat_sectors=`echo "$fat_cyln*$heads*$sectors" | bc`
    echo fat_cyln = $fat_cyln
    echo fat_sectors = $fat_sectors

    echo -n " $usb_device size is "
    print_disk_sizeinfo $usb_device
    echo "Format $usb_device now?"
    select_continue now

    dd if=/dev/zero of=$usb_device bs=512 count=63
    sync;sleep 1;
    sfdisk -R $usb_device
    sfdisk -D $usb_device -H 255 -S 63 -C $total_cyln << EOF
,$fat_cyln,0xc,*
,,0x83,-
EOF
    sync;sync;sync

    sleep 3;
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    if check_mount $usb_device;then 
        err "$usb_device is mounted!"
    fi

    sfdisk -R $usb_device
    #  sfdisk -l $usb_device
    part1_dev=${usb_device}1
    part2_dev=${usb_device}2
    test -b $part1_dev || err "no part $part1_dev"
    test -b $part2_dev || err "no part $part2_dev"
    dd if=/dev/zero of=$part1_dev bs=512 count=1
    dd if=/dev/zero of=$part2_dev bs=512 count=1

    mkfs.vfat -n udisk $part1_dev
    mkfs.ext4 -L sfsroot_usb $part2_dev
    sync;sync;sync

    sleep 3;
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    if check_mount $usb_device;then 
        err "$usb_device is mounted!"
    fi
}

gen_iso_file()
{
    iso_label="sfs_iso"
    iso_filename=$1

    which genisoimage > /dev/null

    install_grub_on_dir $iso_dir
    temp_path=/linux/$zm_arch/${zm_user}
    echo "
menuentry \"ZM($zm_arch) (default)\" --class debian {
set gfxpayload=keep
search --no-floppy -l --set=root $iso_label
echo 'Loading kernel...'
linux $temp_path/$kernel_name sfs_part=cdrom zm_user=$zm_user zm_arch=$zm_arch
echo 'Loading initrd...'
initrd $temp_path/$initrd_name
}
" > $iso_dir/boot/grub/grub.cfg

    #生成iso grub 引导file
    pushd .
    cd $iso_dir/boot/grub/i386-pc
    bootfile=g2hdr
    # grub-mkimage -O i386-pc -o core.img biosdisk ext2 fat iso9660
    grub-mkimage -O i386-pc -o core.img biosdisk iso9660
    cat /usr/lib/grub/i386-pc/cdboot.img core.img > ../$bootfile
    popd

    rm -f $iso_filename
    # “-b”后的文件路径不能是绝对路径，也不能是相对当前目录的路径，只能是相对于ISO源内容目录的路径。
    genisoimage -V $iso_label -R -J -no-emul-boot -boot-load-size 4 -boot-info-table -b boot/grub/$bootfile -o $iso_filename $iso_dir
}

gen_base_softs()
{
    case $zm_arch in
        amd64)
            kernel_softs="linux-image-amd64 linux-headers-amd64"; 
            ;;
        *)
            kernel_softs="linux-image-686-pae linux-headers-686-pae"; 
            ;;
    esac
    zm_base_softs="$kernel_softs grub2 aptitude vim nfs-common udev procinfo 
    hdparm e2fsprogs usbutils lftp less lshw bc initramfs-tools ssh openssh-server
    module-init-tools dosfstools exfat-utils ntfs-3g busybox genisoimage mbr 
    iproute gpm rsync util-linux gpart debootstrap pciutils 
    gzip squashfs-tools aufs-tools locales network-manager"
    # pigz lzip plzip xz-utils pxz p7zip-full
}

zm_chroot()
{
    chroot_dir=$(readlink -f $1)

    cp -fv /etc/resolv.conf $chroot_dir/etc/resolv.conf
    mount_device -t proc -o nosuid,noexec,nodev proc $chroot_dir/proc
    mount_device -t sysfs -o nosuid,noexec,nodev,ro sys $chroot_dir/sys
    mount_device -t devtmpfs -o mode=0755,nosuid udev $chroot_dir/dev
    mount_device -t devpts -o mode=0620,gid=5,nosuid,noexec devpts $chroot_dir/dev/pts
    mount_device -t tmpfs -o mode=1777,nosuid,nodev shm $chroot_dir/dev/shm
    mount_device -t tmpfs -o nosuid,nodev,mode=0755 run $chroot_dir/run
    if [ -d /work/cache/pacman/ ];then
        mkdir -p $chroot_dir/work/cache/pacman
        mount_device --bind /work/cache/pacman $chroot_dir/work/cache/pacman
    fi

    SHELL=/bin/sh unshare --fork --pid chroot $@

    chroot_process=$(lsof -t $chroot_dir) || true
    if [ -n "$chroot_process" ];then
       kill -9 $chroot_process
    fi

    if [ -d /work/cache/pacman ];then
        umount_device $chroot_dir/work/cache/pacman
    fi
    umount_device $chroot_dir/run
    umount_device $chroot_dir/dev/shm
    umount_device $chroot_dir/dev/pts
    umount_device $chroot_dir/dev
    umount_device $chroot_dir/sys
    umount_device $chroot_dir/proc
}

gen_basesystem()
{
    need_root
    defalut_install_dir "$1" "$sfs_part_mpath/linux/$zm_arch/$zm_user"
    print_env

    md5sum_file=$dl_dir/md5sums.txt
    download_file $src_url/archlinux/iso/latest/md5sums.txt $md5sum_file
    bootstrap_file=$(cat $md5sum_file | grep $zm_arch | awk '{print $2}')
    bootstrap_md5=$(cat $md5sum_file | grep $zm_arch | awk '{print $1}')
    download_file $src_url/archlinux/iso/latest/$bootstrap_file /work/cache/pacman/pkg/$bootstrap_file $bootstrap_md5
    root_dir=$build_dir/root.$zm_arch
    if [ ! -d "$root_dir" ];then
        tar xvf /work/cache/pacman/pkg/$bootstrap_file -C $build_dir/
    fi

    echo "Server = $src_url/archlinux/\$repo/os/\$arch" > $root_dir/etc/pacman.d/mirrorlist
    sed -i "s/^#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$cpu_counts\"/g" $root_dir/etc/makepkg.conf

    cp -fv zm_install_pkg $root_dir/root/
    cp -fv zm_install_init $root_dir/root/
    cp -fv pacman.conf $root_dir/etc/pacman.conf
    chmod +x zm_install_pkg $root_dir/root/zm_install_pkg
    chmod +x zm_install_pkg $root_dir/root/zm_install_init

    zm_chroot $root_dir /root/zm_install_init

    rm -fv $root_dir/root/zm_install_init
    rm -fv $root_dir/root/zm_install_pkg

    backup_file $install_dir/${kernel_name}
    backup_file $install_dir/${initrd_name}
    backup_file $install_dir/${root_sfs_name}*

    /bin/cp -fv $root_dir/boot/vmlinuz-linux-aufs_friendly $install_dir/${kernel_name} #no links
    /bin/cp -fv $root_dir/boot/${initrd_name} $install_dir/${initrd_name} #no links
    gen_root_sfs $root_dir $install_dir/${root_sfs_name}
}

gen_initrd()
{
    defalut_install_dir "$1"
    vmlinuz="/boot/vmlinuz-linux-aufs_friendly"
    kernel_ver=$(file "$vmlinuz" | awk '{print $9}')
    mkinitcpio -A sfsroot -S autodetect -k "$kernel_ver" -g ${install_dir}/${initrd_name} 
}

gen_root_sfs()
{
    if [ -e $2 ];then
        /bin/rm -f $2
    fi
    mksquashfs $1 $2 -comp lzo -regex \
        -e "lost+found" -e "sys/.*" -e "proc/.*" -e "run/.*" \
        -e "var/tmp/.*" -e "tmp/.*" \
        -e "media/.*" -e "mnt/.*" -e "dev/disk/.*/.*" \
        -e "etc/mtab" -e "etc/fstab" \
        -e "etc/udev/rules.d/70-.*net.*" \
        -e "etc/hal/fdi/policy/11-x11-vmmouse.fdi" \
        -e "etc/X11/xorg.conf*" \
        -e "usr/portage/distfiles/.*" \
        -e "usr/share/hal/fdi/policy/20thirdparty/11-x11-vmmouse.fdi" \
        -e "usr/bin/vmmouse_detect" \
        -e "var/cache/hald/fdi-cache" \
        -e "var/cache/apt/archives/.*" \
        -e "boot/.*" \
        -e "work/.*" \
        -e "home/.*/.*" 
    touch $1/$aufs_clean_file_name
}

gen_home_sfs()
{
    if [ -e $2 ];then
        /bin/rm -f $2
    fi
    mksquashfs $1 $2 -comp lzo -regex \
        -e ".*/.xauth*" -e ".*/.serverauth" \
        -e ".*/Downloads/.*" \
        -e ".*/.cache" \
        -e ".*/.backup/.*" \
        -e ".*/.xsession-errors" \
        -e ".*/.kermit.log" \
        -e ".*libreoffice.*" 
    touch $1/$aufs_clean_file_name

}

update_system()
{
    need_root
    print_env
    defalut_install_dir $1

    vmlinuz=$(readlink -f /vmlinuz)
    kernel_ver=${vmlinuz#/boot/vmlinuz-}

    # exec -a zm sh -c ""
    echo "#!/bin/bash
    source $zm_dir/common/init_debconf.sh
    db_reset zm_debconf/sfsselect || true
    db_input high zm_debconf/sfsselect || true
    db_go || true
    db_get zm_debconf/sfsselect || true
    echo \$RET > $build_dir/dbconf_ret
    db_stop
    " > $build_dir/zm_debconf
    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf || true

    read sels < $build_dir/dbconf_ret
    echo $sels

    select_continue_debconf

    IFS=', '
    for sel in $sels;do
        case $sel in
            kernel)
                backup_file $install_dir/${kernel_name}
                /bin/cp -f $vmlinuz $install_dir/${kernel_name}
                ;;
            initrd)
                backup_file $install_dir/${initrd_name}
                mkinitramfs -d initramfs -o $install_dir/${initrd_name} $kernel_ver
                ;;
            root)
                backup_file $install_dir/${root_sfs_name}
                gen_root_sfs / $install_dir/${root_sfs_name}
                rm -f $install_dir/${root_sfs_name}.[0-9]
                if [ -e $install_dir/rootaufs.$compress_suffix ];then
                    mv $install_dir/rootaufs.$compress_suffix{,.old}
                fi
                ;;
            home)
                backup_file $install_dir/${home_sfs_name}
                gen_home_sfs /home $install_dir/${home_sfs_name}
                rm -f $install_dir/${home_sfs_name}.[0-9]
                if [ -e $install_dir/homeaufs.$compress_suffix ];then
                    mv $install_dir/homeaufs.$compress_suffix{,.old}
                fi
                ;;
            *)
                ;;
        esac
    done
}

branch_system()
{
    need_root
    defalut_install_dir
    sels="$1"
    if [ -z "$1" ];then
        sels="root home"
    fi
    for sel in $sels;do
        case $sel in
            root)
                for branch in $(seq 1 $aufs_max_branch)
                do
                    if [ ! -e $install_dir/root.sfs.${branch} ];then
                        gen_root_sfs ${aufs_root_mpath}/ $install_dir/root.sfs.$branch
                        break
                    fi
                done
                ;;
            home)
                for branch in $(seq 1 $aufs_max_branch)
                do
                    if [ ! -e $install_dir/home.sfs.${branch} ];then
                        gen_home_sfs ${aufs_home_mpath}/ $install_dir/home.sfs.$branch
                        break
                    fi
                done
                ;;
            *)
                ;;
        esac
    done
}

compress_dir()
{
    file_suffix=$1
    src_dir=$2
    dst_file=$3
    shift 3
    excludes=$@
    case "$file_suffix" in
        tar.gz)
            tar Oc $excludes -C $src_dir . | $GZ -c > $dst_file
            ;;
        tar.lz)
            tar Oc $excludes -C $src_dir . | $LZ -c > $dst_file
            ;;
        tar.xz)
            tar Oc $excludes -C $src_dir . | $XZ -cv - > $dst_file
            ;;
        tar.7z)
            tar Oc $excludes -C $src_dir . |  7z a -t7z -m0=BZip2 -mx=3 -mmt=${cpu_counts} -si $dst_file
            ;;
        *)
            ;;
    esac
}

tar_aufsystem()
{
    install_dir=$1

    if [ -z $install_dir ];then
        install_dir=${sfs_part_mpath}/linux/$zm_arch
        mkdir -p $install_dir
    else
        check_file_exist $install_dir
    fi

    selList=""
    selList+="root root.sfs on "
    selList+="home home.sfs on "

    echo "#!/bin/bash
    source $zm_dir/common/init_debconf.sh
    db_reset zm_debconf/aufsselect || true
    db_input high zm_debconf/aufsselect || true
    db_go || true
    db_get zm_debconf/aufsselect || true
    echo \$RET > $build_dir/dbconf_ret
    db_stop
    " > $build_dir/zm_debconf
    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf || true

    read sels < $build_dir/dbconf_ret
    echo $sels

    IFS=', '
    for sel in $sels;do
        case $sel in
            root)
                if [ -e ${aufs_root_mpath} ];then
                    sfsfile=${install_dir}/rootaufs.$compress_suffix
                    rm -f $sfsfile
                    compress_dir $compress_suffix ${aufs_root_mpath} $sfsfile \
                        --exclude={home/*,work/*,media/*,var/tmp/*,tmp/*,var/*.sock}
                    touch ${aufs_root_mpath}/$aufs_clean_file_name
                fi
                ;;
            home)
                if [ -e ${aufs_home_mpath} ];then
                    sfsfile=${install_dir}/homeaufs.$compress_suffix
                    rm -f $sfsfile
                    compress_dir $compress_suffix ${aufs_home_mpath} $sfsfile \
                        --exclude={*/.cache,*/.xauth,*/*VirtualBox*,var/*.sock}
                    touch ${aufs_home_mpath}/$aufs_clean_file_name
                fi
                ;;
            *)
                ;;
        esac
    done
}

sfs2dir()
{
    7z x $1 -o${2}
}

gen_default_grub_config()
{
    grub_device=$1

    label_param=""
    label_suffix=""
    disk_label=$(e2label $grub_device)
    if echo $disk_label | grep sfsroot;then
        label_suffix=${disk_label/sfsroot}
    fi
    if [ ! -z "$label_suffix" ];then
        label_param="label_suffix=$label_suffix"
    fi

    boot_uuid=$(blkid -s UUID $grub_device | awk -F= '{print $2}' | tr -d '"')
    temp_dir=$(mktemp -d)
    mount_device $grub_device $temp_dir
    temp_path=/linux/$zm_arch/${zm_user}
    echo "
menuentry 'ZM linux $zm_user ($zm_arch)' --class=submenu --class debian {
    set root_uuid=$boot_uuid
    search --no-floppy --fs-uuid --set=root \$root_uuid
    echo 'Loading $zm_arch kernel...'
    linux $temp_path/${kernel_name} sfs_part=UUID=\$root_uuid $label_param zm_user=$zm_user zm_arch=$zm_arch
    echo 'Loading $zm_arch initrd...'
    initrd $temp_path/${initrd_name}
}" > $temp_dir/boot/grub/config/default.cfg
    umount_device $temp_dir
    rmdir $temp_dir
}

gen_iso_system()
{
    iso_file=$1
    test -z "$iso_file" && err "iso file is null"
    install_system $iso_dir
    gen_iso_file $iso_file
}

gen_usb_boot ()
{
    usb_device=$1
    check_file_exist $usb_device

    grub_device=${usb_device}2
    if [ ! -b ${grub_device} ];then
        format_usb_device $usb_device
    fi
    check_file_exist $grub_device
    install_grub $grub_device
    gen_default_grub_config $grub_device
}

gen_usb_system()
{
    usb_device=$1
    check_file_exist $usb_device

    if [ ! -b ${usb_device}2 ];then
        format_usb_device $usb_device
    else 
        disk_id=$(sfdisk --print-id $usb_device 2)
        if [ $disk_id != 83 ];then
            format_usb_device $usb_device
        fi
    fi
    usb_root_device=${usb_device}2
    check_file_exist $usb_root_device

    install_system $usb_root_device 
}

create_virtual_disk()
{
    # disk_format=qcow2
    disk_format=vdi

    root_file=/tmp/zm_root.$disk_format
    work_file=/tmp/zm_work.$disk_format
    root_size=32G
    work_size=32G
    if [ ! -e "$root_file" ];then
        qemu-img create -f $disk_format "$root_file" "$root_size"
    fi
    if [ ! -e "$work_file" ];then
        qemu-img create -f $disk_format "$work_file" "$work_size"
    fi
    qemu-nbd -d /dev/nbd0 || true
    qemu-nbd -d /dev/nbd1 || true
    rmmod nbd || true
    modprobe nbd max_part=16
    qemu-nbd --cache writeback -c /dev/nbd0 $root_file
    qemu-nbd --cache writeback -c /dev/nbd1 $work_file
    # qemu-nbd --cache writethrough -c /dev/nbd0 $root_file
    install-mbr --force /dev/nbd0
    install-mbr --force /dev/nbd1
    sfdisk -D /dev/nbd0 << EOF
,,0x83,*
,,,-
EOF
    sfdisk -D /dev/nbd1 << EOF
,,0x83,*
,,,-
EOF
    while [ ! -e /dev/nbd0p1 ];do
        sfdisk -R /dev/nbd0
        sleep 1
    done
    while [ ! -e /dev/nbd1p1 ];do
        sfdisk -R /dev/nbd1
        sleep 1
    done
    mkfs.ext4 -L sfsroot /dev/nbd0p1
    mkfs.ext4 -L work /dev/nbd1p1

    install_system /dev/nbd0p1

    qemu-nbd -d /dev/nbd0
    qemu-nbd -d /dev/nbd1

    chmod 777 $root_file
    chmod 777 $work_file
    echo "kvm -m 2048 -hda $root_file -hdb $work_file"
}

install_system()
{
    dst=$1

    check_file_exist $root_sfs_file

    if [ "${dst_dir:0:4}" = '/dev' ];then
        if [ ! -b $dst ];then
            err "$dst_dir is not block file."
        fi
    fi
    if [ -b $dst ];then
        mount_device $dst $root_dir
        dst_dir=$root_dir
        install_grub $dst
        gen_default_grub_config $dst
    else
        dst_dir=$dst
        mkdir -p $dst_dir
    fi

    temp_dir=$dst_dir/linux/$zm_arch/$zm_user
    mkdir -p $temp_dir

    $CP $sfs_dir/${kernel_name} $temp_dir
    $CP $sfs_dir/${initrd_name} $temp_dir
    # gen_initrd $dst_dir/linux/$zm_arch/

    rsync -avP $root_sfs_file $temp_dir
    rsync -avP $root_sfs_file.[0-9] $temp_dir || true
    if [ -e $home_sfs_file ];then
        rsync -avP $home_sfs_file $temp_dir
        rsync -avP $home_sfs_file.[0-9] $temp_dir || true
    fi


    sync;sync;sync

    # md5sum $temp_dir/${root_sfs_name}
    # md5sum $temp_dir/${initrd_name}

    if [ -b $dst ];then
        umount_device $dst_dir
    fi
}

add_soft()
{	
    zm_softs+=" "
    zm_softs+="$@"
    # for soft in $@ 
    # do
    # dpkg -s $soft > /dev/null 2>&1 || aptitude install $soft -y
    # done
}

mount_apt_cache()
{
    if mount | grep /work/cache/archives > /dev/null;then
        return
    fi
    if [ -d /work/cache/archives ];then
        mount --bind /work/cache/archives /var/cache/apt/archives
    fi
}

apt_update()
{
    # curl www.baidu.com > /dev/null
    echo "Testing internet connect status..."
    nc -v -w 3 www.baidu.com -z 80
    mount_apt_cache

    if [ ! -e /tmp/.zm_apt_update ];then
        $APTGET update
        touch /tmp/.zm_apt_update
    fi
}

download_softs()
{
    zm_user_command zm_setup_apt
    apt_update
    # aptitude -d -R -y install $zm_softs
    $APTGET -d install $zm_softs || true
    apt-get autoremove || true
    # apt-get autoclean || true
}

install_softs()
{
    download_softs
    # aptitude upgrade -y
    # aptitude -R -y install $zm_softs
    $APTGET upgrade || true
    if $zm_debug;then
        for deb in "$zm_softs"
        do
            $APTGET install $deb || true
        done
    else
        $APTGET install $zm_softs || true
    fi
}

dump_depends()
{
    for deb in "$zm_softs"
    do
        apt-cache -i depends $deb
        # apt-cache --no-suggests depends $deb
    done
    $SUDO apt-get install apt-rdepends
    apt-rdepends -d $zm_softs > /tmp/dep.dot
    cat /tmp/dep.dot | less
    rm /tmp/dep.dot
}

zm_user_command()
{
    cmd=$1
    shift
    test -z "$cmd" && return
    if command -v $cmd > /dev/null 2>&1;then
        $cmd $@
    fi
}

zm_add_groups()
{
    groups="$@"
    for g in $groups
    do
        if ( grep $g /etc/group > /dev/null; ) && ! ( groups $zm_user | grep $g > /dev/null; );then
            usermod -a -G $g $zm_user
        fi
    done
}

cp_mkdir()
{
    dir=$(dirname $2)
    mkdir -p $dir
    $CP $1 $2
}

install_pkg()
{
    install_dir=$1
    if [ -z $install_dir ];then
        install_dir=""
    fi

    cp_mkdir $zm_dir/zm $install_dir/usr/bin/zm
    cp_mkdir $zm_dir/zm_install_pkg $install_dir/usr/bin/zm_install_pkg
    cp_mkdir $zm_dir/hooks/sfsroot $install_dir/etc/initcpio/hooks/sfsroot
    cp_mkdir $zm_dir/install/sfsroot $install_dir/etc/initcpio/install/sfsroot
}

zm_update()
{
    zm_install_pkg http://github.com/Zeroman/zm/raw/master/PKGBUILD
}

zm_setup_tzdata() 
{
    area=$1
    zone=$2
    echo "#!/bin/bash
    . $zm_dir/common/init_debconf.sh

    rm -f /etc/localtime
    rm -f /etc/timezone
    db_set tzdata/Areas '$area' || true
    db_set tzdata/Zones/$area '$zone' || true
    db_fset tzdata/Areas seen true || true
    db_fset tzdata/Zones/$area seen true || true

    " > $build_dir/zm_debconf
    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf
    dpkg-reconfigure -u tzdata || true
}

zm_setup_sh()
{
    default_shell=$1

    case "$default_shell" in
        bash) 
            echo "#!/bin/bash
            . $zm_dir/common/init_debconf.sh
            db_set dash/sh 'false' || true
            db_fset dash/sh seen true || true
            " > $build_dir/zm_debconf
            ;;
        dash)
            echo "#!/bin/bash
            . $zm_dir/common/init_debconf.sh
            db_set dash/sh 'true' || true
            db_fset dash/sh seen true || true
            " > $build_dir/zm_debconf
            ;;
        *)
            return
            ;;
    esac

    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf

    dpkg-reconfigure -u dash || true
}

zm_setup_default_locales()
{
    rm /etc/locale.gen

    echo "#!/bin/bash
    . $zm_dir/common/init_debconf.sh

    db_set locales/locales_to_be_generated 'en_US.UTF-8 UTF-8, zh_CN.GBK GBK, zh_CN.UTF-8 UTF-8'
    db_subst locales/default_environment_locale locales 'en_US.UTF-8, zh_CN.GBK, zh_CN.UTF-8'
    db_set locales/default_environment_locale 'en_US.UTF-8'
    db_fset locales/default_environment_locale seen true
    db_fset locales/locales_to_be_generated seen true

    " > $build_dir/zm_debconf
    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf

    dpkg-reconfigure -u locales || true
}

zm_argv_del()
{
    if [ -n "$1" ];then
        zm_argv=${zm_argv/"$1"}
    fi
}

zm_config()
{
    
    while [ $# -gt 0 ]; do
        case $1 in
            --root-device)  zm_argv_del $1;shift;  root_device=$1; zm_argv_del $1;shift;
                ;;
            --home-device)  zm_argv_del $1;shift; home_device=$1; zm_argv_del $1;shift; 
                ;;
            --swap-device) zm_argv_del $1;shift; swap_device=$1; zm_argv_del $1;shift; 
                ;;
            --root-label) zm_argv_del $1;shift; root_label=$1; zm_argv_del $1;shift; 
                ;;
            --home-label) zm_argv_del $1;shift; home_label=$1; zm_argv_del $1;shift; 
                ;;
            --swap-label) zm_argv_del $1;shift; swap_label=$1; zm_argv_del $1;shift; 
                ;;
            --work-label) zm_argv_del $1;shift; work_label=$1; zm_argv_del $1;shift; 
                ;;
            --root-sfs) zm_argv_del $1;shift; root_sfs_name=$1; zm_argv_del $1;shift; 
                ;;
            --home-sfs) zm_argv_del $1;shift; home_sfs_name=$1; zm_argv_del $1;shift; 
                ;;
            --initrd) zm_argv_del $1;shift; initrd_name=$1; zm_argv_del $1;shift; 
                ;;
            --kernel) zm_argv_del $1;shift; kernel_name=$1; zm_argv_del $1;shift; 
                ;;
            --username) zm_argv_del $1;shift; zm_user=$1; zm_argv_del $1;shift;
                ;;
            --userdir) zm_argv_del $1;shift; zm_user_dir=$1; zm_argv_del $1;shift;
                ;;
            --sfsdir) zm_argv_del $1;shift; sfs_dir=$1; zm_argv_del $1;shift;
                ;;
            --arch) zm_argv_del $1;shift; zm_arch=$1; zm_argv_del $1;shift;
                ;;
            --src-url) zm_argv_del $1;shift; src_url="$1"; zm_argv_del "$1";shift;
                ;;
            --deb-ver) zm_argv_del $1;shift; deb_ver=$1; zm_argv_del $1;shift;
                ;;
            --debug) zm_argv_del $1;shift; zm_debug=true;
                ;;
            *) shift; 
                ;;
      esac
  done

  if $zm_debug;then
      set -x
      CP='/bin/cp -rafv'
  fi

  if $zm_debug;then
      build_dir=/tmp/zm_build
  else
      #can use TMPDIR change, see man mktemp
      build_dir=$(mktemp -d)
  fi

  mnt_dir=$build_dir/mnt
  iso_dir=$build_dir/iso
  sfs_mnt_dir=$build_dir/sfs
  aufs_dir=$build_dir/aufs
  root_dir=$build_dir/root
  dl_dir=$build_dir/dl

  mkdir -p $mnt_dir
  mkdir -p $iso_dir
  mkdir -p $sfs_mnt_dir
  mkdir -p $aufs_dir
  mkdir -p $root_dir
  mkdir -p $dl_dir

  #trap zm_uninit ERR INT QUIT TERM EXIT
  trap zm_uninit ERR INT TERM EXIT


  root_device=/dev/disk/by-label/${root_label}
  home_device=/dev/disk/by-label/${home_label}
  swap_device=/dev/disk/by-label/${swap_label}
  work_device=/dev/disk/by-label/${work_label}

  if [ -z "$zm_user" ];then
      if [ -z "$SUDO_USER" ];then
          zm_user=$USER
      else
          zm_user=$SUDO_USER
      fi
  fi

  if [ -z "$sfs_dir" ];then
      sfs_dir=$sfs_part_mpath/linux/$zm_arch
      if [ -d "$sfs_dir/$zm_user" ];then
          sfs_dir="$sfs_part_mpath/linux/$zm_arch/$zm_user"
      fi
  fi
  root_sfs_file=$sfs_dir/${root_sfs_name}
  home_sfs_file=$sfs_dir/${home_sfs_name}
  kernel_file=$sfs_dir/${kernel_name}
  initrd_file=$sfs_dir/${initrd_name}

  zm_user_home=$(grep $zm_user /etc/passwd | awk -F:  '{print $6}')
  if [ -z "$zm_user_dir" ];then
      if [ -d $zm_user_home/.zm ];then
          zm_user_dir=$zm_user_home/.zm/
      else
          if [ -d $zm_dir/user/$zm_user ];then
              zm_user_dir=$zm_dir/user/$zm_user
          fi
      fi
  fi

  if [ -e $zm_user_dir/config.sh ];then
      source $zm_user_dir/config.sh
  fi

  zm_user_command zm_user_init

  gen_base_softs
  zm_softs=$zm_base_softs
  zm_user_command zm_add_softs
}

zm_excute()
{
    while [ $# -gt 0 ]; do
        case $1 in
            --install-grub) shift; install_grub $1; test -z "$1" || shift; 
                ;;
            --gen-basesystem) shift; gen_basesystem $1; test -z "$1" || shift; 
                ;;
            --install-system) shift; install_system $1; test -z "$1" || shift; 
                ;;
            --gen-initrd) shift; gen_initrd $1; test -z "$1" || shift; 
                ;;
            --update-system|-u) shift; update_system $1; test -z "$1" || shift; 
                ;;
            --branch-system|-b) shift; branch_system $1; test -z "$1" || shift; 
                ;;
            --gen-iso-system) shift; gen_iso_system $1; test -z "$1" || shift; 
                ;;
            --gen-usb-system) shift; gen_usb_system $1; test -z "$1" || shift; 
                ;;
            --gen-usb-boot) shift; gen_usb_boot $1; test -z "$1" || shift;
                ;;
            --download-softs|-d) download_softs; shift;
                ;;
            --install-softs) install_softs; shift
                ;;
            --debconf-softs) zm_user_command debconf_softs; shift 
                ;;
            --setup) zm_user_command zm_setup; shift
                ;;
            --tar-aufssystem) shift; tar_aufsystem $1; test -z "$1" || shift
                ;;
            --install-pkg) shift; install_pkg $1; exit 0;
                ;;
            --update-pkg) zm_update; exit 0;
                ;;
            --edit|-e) $EDITOR $zm_path; exit 0;
                ;;
            --chroot)  shift; zm_chroot $1; exit 0;
                ;;
            *) 
                echo "$1"
                type -t "$1" > /dev/null && { echo "run $1";$1; }; shift
                ;;
      esac
    done
}

zm_init()
{
    CP='/bin/cp -raf'
    APTGET='apt-get --no-install-recommends --no-install-suggests --yes'

    cpu_counts=`cat /proc/cpuinfo | grep "processor" | wc -l`

    GZ=gzip
    LZ=lzip
    XZ=xz

    which pigz > /dev/null 2>&1 && GZ="pigz -p $cpu_counts"
    which plzip > /dev/null 2>&1 && LZ="plzip -n $cpu_counts"
    which pxz > /dev/null 2>&1 && XZ="pxz -T$cpu_counts"

    which mksquashfs > /dev/null
    which install-mbr > /dev/null

    root_label=root
    home_label=home
    swap_label=swap
    work_label=work

    root_path=""
    home_path='home'
    work_path='work'

    root_sfs_name="root.sfs"
    home_sfs_name="home.sfs"
    initrd_name="initrd.img"
    kernel_name="vmlinuz"

    sfs_dir=""
    zm_user=""
    zm_user_dir=""


    # deb_ver=testing
    deb_ver=unstable
    zm_arch='x86_64'
    compress_suffix="tar.gz"
    aufs_max_branch=8

    # no multimedia
    # src_url=http://mirrors.163.com
    # src_url=http://mirrors.aliyun.com
    # src_url=http://mirrors.sohu.com

    # have multimedia
    # src_url=http://free.nchc.org.tw
    src_url=http://mirrors.ustc.edu.cn
    # src_url=http://mirrors.xmu.edu.cn
    # src_url=http://mirror.bjtu.edu.cn

    zm_softs=""

}

zm_uninit()
{
    trap - ERR INT TERM EXIT
    if [ -d $build_dir ];then
        if $zm_debug;then
            echo "$zm_path $zm_argv Clean ..."
        fi
        if [ -e $build_dir/.mount_devs ];then
            devs=`cat $build_dir/.mount_devs`
            for dev in $devs;do
                echo "umount $dev"
                umount_device $dev || true
            done
            rm -rf $build_dir/.mount_devs
        fi
        check_mount $build_dir || true
        if $zm_debug;then
            echo "In debug mode, please manual delete $build_dir"
        else
            rm -rf $build_dir 
        fi
    fi
}

###############################################################################
###############################################################################
###############################################################################

if [ $# -eq 0 -o "$1" = "--help" ];then
    usage
    exit 0
fi

zm_argv=$@
zm_clean=true
zm_debug=false

export zm_debug

zm_init
zm_config $zm_argv
zm_excute $zm_argv
zm_uninit


