#!/bin/sh

if  [ ! -e /etc/pacman.d/gnupg/trustdb.gpg ];then
    pacman-key --init
    pacman-key --populate archlinux
fi
pacman -Suy --noconfirm
pacman -S --needed --noconfirm vim openssh wget dosfstools base-devel
pacman -S --needed --noconfirm procps-ng
pacman -S --needed --noconfirm xmlto docbook-xsl inetutils bc git
#yaourt
#pacman -S --noconfirm abs; abs;abs;abs

/root/zm_install_pkg package-query
/root/zm_install_pkg yaourt
/root/zm_install_pkg linux-aufs_friendly --skippgpcheck
/root/zm_install_pkg mbr
/root/zm_install_pkg http://github.com/Zeroman/zm/raw/master/PKGBUILD

zm --gen-initrd /boot/
echo root:root | chpasswd
