#!/bin/sh

useradd build_user
echo "%build_user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/build_user
mkdir -p /tmp/build
cd /tmp/build
pkgname=$1
if [ "${pkgname:(-8)}" = "PKGBUILD" ];then
    wget $pkgname
    pkgname=$(awk -F= '/pkgname=/{print $2}' PKGBUILD)
    # pacman -Qq $pkgname > /dev/null 2>&1 && exit
else
    pacman -Qq $pkgname > /dev/null 2>&1 && exit
    wget http://aur.archlinux.org/packages/${pkgname:0:2}/${pkgname}/${pkgname}.tar.gz
    tar xvf ${pkgname}.tar.gz
    cd ${pkgname}
fi
chown build_user.build_user /tmp/build -R
su build_user -c "makepkg --noconfirm -si $2"
repo_dir=/work/cache/pacman/repo
if [ -d $repo_dir ];then
    rm -fv $repo_dir/${pkgname}*pkg.tar.[xg]z
    cp -fv ${pkgname}*pkg.tar.[xg]z $repo_dir/
    rm -fv $repo_dir/custom.db.tar.gz
    repo-add $repo_dir/custom.db.tar.gz $repo_dir/*.pkg.tar.[xg]z
fi
userdel build_user
rm -f /etc/sudoers.d/build_user
rm -rf /tmp/build

