#!/bin/sh


install_pkg()
{
    if pacman -Ssq "^$1$" > /dev/null;then
        pacman -S --needed --noconfirm $1
        return
    fi

    if [ -z "$2" ];then
        /root/zm_install_pkg $1
    else
        /root/zm_install_pkg $2
    fi
}

if  [ ! -e /etc/pacman.d/gnupg/trustdb.gpg ];then
    pacman-key --init
    pacman-key --populate archlinux
fi
pacman -Suy --noconfirm
pacman -S --needed --noconfirm vim openssh wget dosfstools base-devel
pacman -S --needed --noconfirm procps-ng
pacman -S --needed --noconfirm xmlto docbook-xsl inetutils bc git
#yaourt
#pacman -S --noconfirm abs; abs;abs;abs

install_pkg package-query
install_pkg yaourt
install_pkg mbr
install_pkg linux-aufs_friendly --skippgpcheck
install_pkg aufs3
install_pkg aufs3-util
install_pkg zm http://github.com/Zeroman/zm/raw/master/PKGBUILD

zm --gen-initrd /boot 
echo root:root | chpasswd
